In [1]:
import numpy as np

In [2]:
ans_overall = []

In [3]:
ans = np.array([]).reshape(0,3)

In [4]:
k = np.array([[1,2,3]])

In [5]:
k

array([[1, 2, 3]])

In [6]:
ans = np.vstack([ans, k])
print(ans)
ans = np.vstack([ans, k])
print(ans)

[[1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]]


In [7]:
ans.shape

(2, 3)

In [8]:
ans

array([[1., 2., 3.],
       [1., 2., 3.]])

In [9]:
print(u"\u00B1")

±
